### Spring properties
# Service registers under this name
spring:
  zipkin:
    base-url: http://localhost:7777/
  sleuth:
   sampler:
    probability: 1
  application:
    name: ChildOne-microservice
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/classroom_chat
    username: root
    password: suman013
  jpa:
    hibernate:
      ddl-auto: update
    
firstRibbon:
  ribbon:
    listOfServers : http://localhost:5550,http://localhost:5551
    eureka:
      enabled: false
    ServerListRefreshInterval: 1000

# Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:1111/eureka/

# HTTP Server (Tomcat) Port
server: 
  port: 4444

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: false
   
##Mysql
#spring:

    
#spring.jpa.hibernate.ddl-auto=update
##spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}/db_example
#spring.datasource.url=jdbc:mysql://localhost:3306/classroom_chat
#spring.datasource.username=root
#spring.datasource.password=suman013
#spring.jpa.hibernate.ddl-auto=update
 
#spring:
#  sleuth:
#    sampler:
#      probability:1
