### Spring properties
# Service registers under this name
spring:
  zipkin:
    base-url: http://localhost:7777/
  sleuth:
   sampler:
    probability: 1
  application:
    name: ChildThird-microservice
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/classroom_chat
    username: root
    password: suman013
  jpa:
    hibernate:
      ddl-auto: update

# Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:1111/eureka/

# HTTP Server (Tomcat) Port
server: 
  port: 4444

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: false